bns/blog/urls.py
from django.urls import path
from .views import PostListView, PostDetailView, PostCreateView, PostUpdateView, PostDeleteView, UserPostListView, \
    PurchaseItemView
from . import views

# .as_view for class based views
# use variables for single post views!
# detailView expects 'pk' in the variables
urlpatterns = [
    path('', PostListView.as_view(), name='blog-home'),
    path('about/', views.about, name='blog-about'),
    path('post/<int:pk>/', PostDetailView.as_view(), name='post-detail'),
    path('post/new/', PostCreateView.as_view(), name='post-create'),
    path('post/<int:pk>/update', PostUpdateView.as_view(), name='post-update'),
    path('post/<int:pk>/delete', PostDeleteView.as_view(), name='post-delete'),
    path('user/<str:username>', UserPostListView.as_view(), name='user-posts'),
    path('post/<int:pk>/comment', views.post_detail_view, name='post-comment'),
    path('post/<int:pk>/purchase', PurchaseItemView.as_view(), name='post-purchase'),
]


# when class view used, it is looking for a specific pattern:
# <app>/<model>_<viewtype>.html, so in our case that would be blog/

bns/bns/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from users import views as user_views

urlpatterns = [
    path('profile/', user_views.profile, name='profile'),
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('register/', user_views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('password-reset/',
         auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'),
         name='password_reset'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
]

# this serves user-uploaded media files, more info on
# https://docs.djangoproject.com/en/2.1/howto/static-files/#serving-files-uploaded-by-a-user-during-development
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# TODO add updating of the user profile

bns/blog/models.py
from PIL import Image
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone
from django.urls import reverse


def post_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/post_<author>/<filename>
    return 'post_{0}/{1}'.format(instance.author, filename)


class Post(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    # to change the time to be constant after post creation, set DateTimeField to auto_now_add=True
    date_posted = models.DateTimeField(default=timezone.now)
    # CASCADE - if the user deleted, posts of that user are deleted too
    # use SET() to pass an author (i.e. "author deleted")
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    price = models.DecimalField(default=0, max_digits=6, decimal_places=2)
    image = models.ImageField(default='default_item.jpg', blank=True, upload_to=post_directory_path)

    def __str__(self):
        return self.title
    # There are two ways doing the redirection after post creation. If we want to see the post created
    # in its own view, we use the following,
    # If we want it to just jump to home page, go to blog/views and see success_url
    # def get_absolute_url(self):
    #     # this is going to send us to the newly created post page after creating it
#     # return reverse('post-detail', kwargs={'pk':self.pk})

    def save(self, *args, **kwargs):
        # resizing images because we can, using pillow library mentioned in class
        super(Post, self).save(*args, **kwargs)
        img = Image.open(self.image.path)
        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.image.path)


class Images(models.Model):
    post = models.ForeignKey(Post, default=None, on_delete=models.CASCADE)
    image = models.ImageField(upload_to="items/images", null=True, blank=True)

    def __str__(self):
        return self.post.title + " Img"


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=False)

    class Meta:
        ordering = ['created_on']

    def __str__(self):
        return 'Comment {} by {}'.format(self.content, self.user)

bns/blog/forms.py
from django import forms
from .models import Post, Images, Comment


class PostForm(forms.ModelForm):
    title = forms.CharField(max_length=128)
    text = forms.CharField(max_length=245, label="Item Description.")
    price = forms.DecimalField(max_digits=6, decimal_places=2)

    class Meta:
        model = Post
        fields = ('title', 'text', 'price')


class ImageForm(forms.ModelForm):
    image = forms.ImageField(label='Image')

    class Meta:
        model = Images
        fields = ('image',)


class CommentForm(forms.ModelForm):
    content = forms.CharField(max_length=255)

    class Meta:
        model = Comment
        fields = ('user', 'content',)

bns/blog/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from .forms import ImageForm, PostForm, CommentForm
from .models import Post, Images, Comment
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.models import User
from django.forms import modelformset_factory
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin


# views handle routes to html pages, generally speaking

# def home(request):
#     context = {
#         'posts': Post.objects.all()
#     }
#     return render(request, 'blog/home.html', context)
# since we created a class based view, we dont need those lines of code anymore anyway


class PostListView(ListView):  # to display homepage with posts
    model = Post
    template_name = 'blog/home.html'
    context_object_name = 'posts'
    # when class view used, it is looking for a specific pattern:
    # <app>/<model>_<viewtype>.html, but we can override
    #       and also set another variable so it does not look for 'list'
    ordering = ['-date_posted']  # this would put newer ads first
    paginate_by = 10


class UserPostListView(ListView):  # to display homepage with posts
    model = Post
    template_name = 'blog/user_posts.html'
    context_object_name = 'posts'
    # when class view used, it is looking for a specific pattern:
    # <app>/<model>_<viewtype>.html, but we can override
    #       and also set another variable so it does not look for 'list'
    paginate_by = 10

    def get_queryset(self):
        user = get_object_or_404(User, username=self.kwargs.get('username'))
        return Post.objects.filter(author=user).order_by('-date_posted')


class PurchaseItemView(LoginRequiredMixin, SuccessMessageMixin, UserPassesTestMixin, UpdateView):
    model = Post
    fields = ['price', ]
    template_name = 'blog/post_purchase.html'
    success_url = reverse_lazy('blog-home')
    success_message = "Item was purchased."

    def form_valid(self, form):
        self.request.user.profile.moneys -= form.instance.price  # taking money from current user
        form.instance.author.profile.moneys += form.instance.price  # giving money to the author
        form.instance.author.profile.save()
        self.request.user.profile.save()
        form.instance.author = self.request.user  # assigning the post author to the buyer
        return super().form_valid(form)

    # self.request.user.profile.moneys is the current user (buyer) money
    # form.instance.price price of the post
    # part of mixins, blocks users from editing other user's posts
    def test_func(self):
        post = self.get_object()
        if self.request.user != post.author:
            return True
        return False


# view for each individual post
#
class PostDetailView(DetailView):  # each single post page
    model = Post


class PostCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):  # creating new post view
    model = Post
    fields = ['title', 'content', 'price', 'image']
    success_url = reverse_lazy('blog-home')
    success_message = "Post  about %(title)s was created"

    #  need to override for to set an author for the post
    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class PostUpdateView(LoginRequiredMixin, SuccessMessageMixin, UserPassesTestMixin,
                     UpdateView):
    model = Post
    fields = ['title', 'content', 'price', 'image']
    success_url = reverse_lazy('blog-home')
    success_message = "Post  about %(title)s was updated"

    #  need to override for to set an author for the post
    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    # part of mixins, blocks users from editing other user's posts
    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False


class PostDeleteView(LoginRequiredMixin, SuccessMessageMixin, UserPassesTestMixin, DeleteView):  # each single post page
    model = Post
    success_message = "Post  about %(title)s was deleted"
    success_url = reverse_lazy('blog-home')

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False


# about page, nothing here yet anyway
def about(request):
    return render(request, 'blog/about.html', {'title': 'About'})


def post_detail_view(request, pk):
    template_name = 'blog/comment_form.html'
    post = get_object_or_404(Post, pk=pk)
    new_comment = None

    comment_form = CommentForm(data=request.POST or None)
    if comment_form.is_valid():
        # Create Comment object but don't save to database yet
        new_comment = comment_form.save(commit=False)
        # Assign the current post to the comment
        new_comment.post = post
        # Save the comment to the database
        messages.success(request, f'Comment posted successfully!')
        new_comment.save()
        return redirect('blog-home')
    else:
        comment_form = CommentForm()

    return render(request, template_name, {'new_comment': new_comment,
                                           'comment_form': comment_form}, )

bns/blog/templates/blog/about.html
{% extends 'blog/base.html' %}
{% block content %}
    <h1>About</h1>
	<p>We are a group of Computer Science students from Dawson College. This is the About page of the Django Stuff Exchange,
	which was primarily bases on how Kijiji works, for the most part. On this page, you - the client will be able to create
	your account, which enables you to post things that you want to sell, comment on others' posts and delete your own post. 
	</p>
{% endblock content %}

bns/blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'blog/main.css' %}">
    {% if title %}
        <title>Django Buy and Sell - {{ title }}</title>
    {% else %}
        <title>Django Buy and Sell</title>
    {% endif %}
</head>
<body>
<header class="site-header">
    <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
            <a class="navbar-brand mr-4" href="/">Django Stuff Exchange</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle"
                    aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarToggle">
                <div class="navbar-nav mr-auto">
                    <a class="nav-item nav-link" href="{% url 'blog-home' %}">Home</a>
                    <a class="nav-item nav-link" href="{% url 'blog-about' %}">About</a>
                </div>
                <!-- Navbar Right Side -->
                <div class="navbar-nav">
                    {% if user.is_authenticated %}
                        <a class="nav-item nav-link" href="{% url 'post-create' %}">New Post</a>
                        <a class="nav-item nav-link" href="{% url 'logout' %}">Logout</a>
                        <a class="nav-item nav-link" href="{% url 'profile' %}">Profile</a>
                    {% else %}
                        <a class="nav-item nav-link" href="{% url 'login' %}">Login</a>
                        <a class="nav-item nav-link" href="{% url 'register' %}">Register</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </nav>
</header>

<main role="main" class="container">
    <div class="row">
        <div class="col-md-8">
            {% if messages %}
                {% for message in messages %}
                    <div class="alert alert-{{ message.tags }}">
                        {{ message }}
                    </div>
                {% endfor %}
            {% endif %}
            {% block content %}{% endblock %}
        </div>
        <div class="col-md-4">
            <div class="content-section">
                {% if user.is_authenticated %}
                    <h3 class="nav-item nav-link">Hello, {{ user.username }}!</h3>
                {% endif %}
                <h4>Your Sidebar</h4>
                <p class='text-muted'>Here you can find useful links and information about your account.</p>
                <ul class="list-group">
                    <li class="list-group-item list-group-item-light"><a class="text-decoration-none link-info" href="{% url 'blog-home' %}">Latest Posts</a></li>
                    <li class="list-group-item list-group-item-light">Announcements</li>
                {% if user.is_authenticated %}
                    <li class="list-group-item list-group-item-light">
                        <a class="text-decoration-none link-info" href="{% url 'user-posts' user.username %}">Your Posts</a>
                    </li>
                    <li class="list-group-item list-group-item-light">Balance: {{ user.profile.moneys }}</li>
                {% endif %}
                </ul>
            </div>
        </div>
    </div>
</main>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf"
        crossorigin="anonymous"></script>
</body>
</html>

bns/blog/templates/blog/comment_form.html
{% extends 'blog/base.html' %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST" enctype="multipart/form-data">

            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Comment</legend>
                {{ comment_form|crispy }}
            </fieldset>
            <div class="form-group mt-3">
                <button type="submit" class="btn btn-primary  btn-lg">Submit</button>
            </div>
        </form>
    </div>
{% endblock content %}

bns/blog/templates/blog/home.html
{% extends 'blog/base.html' %}
{% block content %}
    {% for post in posts %}
        <article class="media content-section">
            <img src="{{ post.author.profile.image.url }}" class="rounded-circle article-img" alt="profile pic">
            <div class="media-body">
                <div class="article-metadata">
                    <a class="mr-2" href="{% url 'user-posts' post.author.username %}">{{ post.author }}</a>
                    <small class="text-muted">{{ post.date_posted }}</small>
                    <p class="small">Price: {{ post.price }}</p>
                    {#  to filter date: post.date_posted| date:"F d, Y"(fullmonth day, year)#}
                </div>
                <h2><a class="article-title" href="{% url 'post-detail' post.id %}">{{ post.title }}</a> </h2>
                <p class="article-content">{{ post.content }}</p>
                <img src="{{ post.image.url }}" alt="">
                <div class="row">
                <br>
                {% for pic in post.images_set.all %}
                    <div class="col-md-4">
                        <img src="{{ pic.image.url }}" class="img-fluid">
                    </div>
                {% endfor %}
            </div>
            </div>
        </article>
    {% endfor %}
{#    next snippet is formats the pagination and shows page numbers, just like kijiji#}
    {% if is_paginated %}
        {% if page_obj.has_previous%}
            <a class="btn btn-outline-info mb-4" href="?page=1">First Page</a>
            <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>
        {% endif %}
        {% for num in page_obj.paginator.page_range %}
            {% if page_obj.number == num %}
                <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
            {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
            {% endif %}
        {% endfor %}
        {% if page_obj.has_next%}
            <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
            <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last Page</a>
        {% endif %}

    {% endif %}
{% endblock content %}

bns/blog/templates/blog/post_confirm_delete.html
{% extends 'blog/base.html' %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Delete Post</legend>
                <h2>Are you sure you want to delete "{{ object.title }}"</h2>
            </fieldset>
            <div class="form-group mt-3">
                <button class="btn btn-outline-danger" type="submit">I agree to delete</button>
                <a class="btn btn-outline-secondary" href="{% url 'post-detail' object.id %}">Back to the post</a>

            </div>
        </form>
    </div>
{% endblock content %}

bns/blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}

{% block content %}
{#    have to change post. to object. due to django naming convention#}
    <article class="media content-section">
        <img src="{{ object.author.profile.image.url }}" class="rounded-circle article-img" alt="profile pic">
        <div class="media-body">
            <div class="article-metadata">
                <a class="mr-2" href="{% url 'user-posts' object.author.username %}">{{ object.author }}</a>
                <small class="text-muted">{{ object.date_posted }}</small>
                <p class="text-capitalize">Price: {{ post.price }}</p>
                {% if object.author == user %}
                    <div>
                        <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'post-update' object.id %}">Update</a>
                        <a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'post-delete' object.id %}">Delete</a>
                    </div>
                {% else %}
                    <div>
                        {% if user.is_authenticated %}
                            <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'post-purchase' object.id  %}">Purchase with coins</a>
                        {% else %}
                            <a class="btn btn-outline-info mb-2" href="{% url 'login' %}">Login to purchase</a>
                        {% endif %}
                    </div>
                {% endif %}
                {#  to filter date: post.date_posted| date:"F d, Y"(fullmonth day, year)#}
            </div>
            <h2 class="article-title">{{ object.title }}</h2>
            <p class="article-content">{{ object.content }}</p>
            <img src="{{ object.image.url }}" alt="">
            <div class="row">
                {% for pic in post.images_set.all %}
                    <div class="col-md-4">
                        <img src="{{ pic.image.url }}" class="img-fluid" alt="">
                    </div>
                {% endfor %}
            </div>
        </div>
    </article>

    <div class="col-md-8 card mb-4  mt-3 ">
      <div class="card-body">
        <!-- comments -->
        <h3>{{ post.comments.count }} Comments</h3>

        {% for comment in post.comments.all %}
        <div class="comments" style="padding: 10px;">
          <p class="font-weight-bold">
            {{ comment.user }}
            <span class=" text-muted font-weight-normal">
              {{ comment.created_on }}
            </span>
          </p>
                {{ comment.content | linebreaks }}
        </div>
        {% endfor %}
      <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'post-comment' object.id %}">Comment</a>
      </div>
    </div>

{% endblock content %}

bns/blog/templates/blog/post_form.html
{% extends 'blog/base.html' %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">

        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Post an ad</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group mt-3">
                <button class="btn btn-outline-info">Post</button>
            </div>
        </form>
    </div>
{% endblock content %}

bns/blog/templates/blog/post_purchase.html
{% extends 'blog/base.html' %}
{% load crispy_forms_filters %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Purchase Item</legend>
                <h2>Are you sure you want to purchase this item for {{ object.price }}?</h2>
                <p>Please set a new price:</p>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group mt-3">
                <button class="btn btn-outline-success" type="submit">I agree to pay</button>
                <a class="btn btn-outline-secondary" href="{% url 'post-detail' object.id %}">Back to the post</a>
            </div>
        </form>
    </div>
{% endblock content %}

bns/blog/templates/blog/user_posts.html
{% extends 'blog/base.html' %}
{% block content %}
    <h1 class="mb-3">Posts by {{ view.kwargs.username }} ({{ page_obj.paginator.count }})</h1>
    {% for post in posts %}
        <article class="media content-section">
            <img src="{{ post.author.profile.image.url }}" class="rounded-circle article-img" alt="profile pic">
            <div class="media-body">
                <div class="article-metadata">
                    <a class="mr-2" href="{% url 'user-posts' post.author.username %}">{{ post.author }}</a>
                    <small class="text-muted">{{ post.date_posted }}</small>
                    <p class="text-capitalize">Price: {{ post.price }}</p>
                    {#  to filter date: post.date_posted| date:"F d, Y"(fullmonth day, year)#}
                </div>
                <h2><a class="article-title" href="{% url 'post-detail' post.id %}">{{ post.title }}</a></h2>
                <p class="article-content">{{ post.content }}</p>
                <img src="{{ post.image.url }}" alt="">
            </div>
        </article>
    {% endfor %}
{#    next snippet is formats the pagination and shows page numbers, just like kijiji#}
    {% if is_paginated %}
        {% if page_obj.has_previous%}
            <a class="btn btn-outline-info mb-4" href="?page=1">First Page</a>
            <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>
        {% endif %}
        {% for num in page_obj.paginator.page_range %}
            {% if page_obj.number == num %}
                <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
            {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
            {% endif %}
        {% endfor %}
        {% if page_obj.has_next%}
            <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
            <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last Page</a>
        {% endif %}

    {% endif %}
{% endblock content %}